spring.application.name=SpringProject

#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html

#server.servlet.context-path=/VITproject

#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:file:./db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Insert into DB for admin user
#INSERT INTO USERS (user_id, user_email, user_firstname, oauth2_user, user_password, user_phone) VALUES (1, 'admin@gmail.com', 'ADMIN', false, '$2a$12$.Xyh361kY6CWBX52sWMBNO6lnE5kqp3AEZ3Fgeq4y7d0IN3R0hGpu', '9606149003');

#Insert roles in DB
#INSERT INTO ROLES (role_id, role_name) VALUES (1, 'ROLE_ADMIN'), (2, 'ROLE_USER')

#Insert admin role in DB
#INSERT INTO USER_ROLE (user_id, role_id) VALUES (1,1),(1,2);

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://database-1.cvsiwgo6olhl.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=anoop.postgresql2003!

spring.jpa.properties.hibernate,dialect = org.hibernate.dialect.PostgreSQLDialect

# This will create table automatically in your database
#spring.jpa.hibernate.ddl-auto=create  
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

server.port=8080

#Oauth2 configuration    https://console.cloud.google.com/welcome?project=ecommercespringmajor
spring.security.oauth2.client.registration.google.client-id=610342059441-spt63na5f8r39h9io6rct2aqvqihfrm0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=https://springboot-ecommerce-project-lkfh.onrender.com/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid, profile, email
#spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

#----------REMEMBER_ME TOKEN PRIVATE KEY---------------
rememberMe.privateKey=12345

#----------Paytm_Sandbox_Configuration-----------------
paytm.merchant-id=YOUR_MERCHANT_ID
paytm.merchant-key=YOUR_MERCHANT_KEY
paytm.website=WEBSTAGING
paytm.industry-type-id=Retail
paytm.channel-id=WEB
paytm.paytm-url=https://securegw-stage.paytm.in/theia/processTransaction


# paytm.payment.sandbox.merchantId:
# paytm.payment.sandbox.merchantKey: 
# paytm.payment.sandbox.channelId:WEB
# paytm.payment.sandbox.industryTypeId:Retail
# paytm.payment.sandbox.website:WEBSTAGING
# paytm.payment.sandbox.paytmUrl:https://securegw-stage.paytm.in/order/process
# paytm.payment.sandbox.callbackUrl:http://localhost:8080/pgresponse
# paytm.payment.sandbox.details.MID: ${paytm.payment.sandbox.merchantId}
# paytm.payment.sandbox.details.CHANNEL_ID: ${paytm.payment.sandbox.channelId}
# paytm.payment.sandbox.details.INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industryTypeId}
# paytm.payment.sandbox.details.WEBSITE: ${paytm.payment.sandbox.website}
# paytm.payment.sandbox.details.CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}
# paytm.mobile = 
# paytm.email 

#CoinGecko api url
#crypto.api.url=https://api.coingecko.com/api/v3
#crypto.user.agent=SpringProject/1.0 (https://springboot-ecommerce-project-lkfh.onrender.com)

#live inr eth rate
crypto.api.url=https://min-api.cryptocompare.com

#gmail id used in twilio is anoopsen0802@gmail.com (free tier user)

twilio.account_sid=ACbd84b2a711280489f60af46589ccd578
twilio.auth_token=d3071a5cf456eda8f0cca7360db7af33
#This phone number was given to us from twilio.com for demo purposes, this will be the number which will send the OTP to our number
twilio.trial_number=+13045841237

# Email Configuration
#spring.mail.host=your_smtp_server_host
#spring.mail.port=your_smtp_server_port
#spring.mail.username=your_email_username
#spring.mail.password=your_email_password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Infura Sepolia URL with your Project ID: Infuria is the public node provider, and Sepolia is the Ethereum public testnet which infuria public node interacts with.
service.url=https://sepolia.infura.io/v3/cb295e2bcc5c4ae0a59a5a9ad2b10b6c
